In [1]:
import hashlib
import numpy as np
import aeskeyschedule as aes
from Crypto.Cipher import AES
from tqdm import tqdm

In [2]:
import math


def hex_to_int(hex_str):
    return int(hex_str.replace(" ", "").replace("\n", ""), 16)


N_hex = """
9B 1F 16 A7 69 6A C9 0F A7 AE 61 5A 1F 71 BD 1A 
C0 C3 1B 37 A9 F1 43 76 BE C7 FB 70 14 12 F0 E3 
B7 9C AB 88 F9 06 B3 50 B5 21 57 87 66 C7 8C AC 
D2 E8 06 32 D0 93 5F 50 CD DC 41 5D C1 B0 46 EB 
3B 35 56 62 4E B4 12 D0 56 F8 73 E5 A0 56 C2 B8 
5B 36 4D 03 2B BA A9 27 67 57 B0 58 87 9B 02 CB 
20 98 D6 3C 61 55 1D 47 53 B1 AE 18 90 D8 FF 79 
BA 10 F8 23 07 49 2A 77 5A 57 15 AD 60 5B 56 01
"""

s_hex = """
14 48 FA 66 0D 3D EE 69 3A 9A E1 0E 3D BE 17 6D 
D0 AE 96 37 F2 89 60 03 36 7F AB 3F 71 C1 BE 2C 
8A 14 3D D9 E4 16 7C 9A 07 80 1E 66 6A C2 68 F3 
76 EE 6B 9A 27 75 23 22 E1 BB D1 6F 8D DA 2B 90 
05 8A 07 B1 AB 56 45 37 C8 00 95 3B D2 37 71 D8 
CF D0 8B 96 D3 4B A6 01 3B 10 38 3B 19 D0 F2 63 
E0 EE BC 7D 09 FD FE A0 03 D7 3D DA 88 5D 25 A3 
C2 87 0C F8 E5 FF E7 20 1A E7 58 74 F3 83 09 7B
"""

s_faulty_hex = """
9A BD 38 BD D4 61 B4 F8 F6 A1 82 4B 1B 43 D4 1C 
18 31 90 71 CA 60 28 86 55 76 C3 2A 25 85 32 BB 
08 A4 49 F2 93 72 F4 BD B0 16 B5 A1 F5 7A AA 96 
BE 66 B1 7E CF 0C D2 BF 89 C7 CA C7 7E 5B 1A 43 
46 06 88 C3 ED BF 6D A6 EB CE EA 9B 57 97 A4 FC 
28 EC 93 EF 18 DA 6E E5 4A 52 38 61 AB ED C8 2C 
4A 14 8E C5 C8 8D E1 C5 1B 6C 81 3C 8C 13 17 3E 
85 26 D0 03 5E 2A 37 5C F7 22 2A 18 C2 86 0B 1A
"""


N = hex_to_int(N_hex)
s = hex_to_int(s_hex)
s_faulty = hex_to_int(s_faulty_hex)


p = math.gcd(N, s - s_faulty)


q = N // p


assert p * q == N, "incorrect"


print(f"q = {hex(p)}")
print(f"p = {hex(q)}")


q = 0x9f44ddf28f05904455669a629df988adf203812f56aa8047c7db9bb7b4e61dd67b027e80d8700a77471943cc76370ced07056ef808a12b2a467c159e586c33
p = 0xf9555b790d60dcb3fdcdf464b88ab7bb629bfce037f4154927df19fcdb1b4c7327d41b17d848455cffbda7e8080c08600be3af126df6c481ab25da70bec471c0fb


In [3]:
import math


def hex_to_int(hex_str):
    return int(hex_str.replace(" ", "").replace("\n", ""), 16)


N_hex = """
C2 D2 BE 8E 72 2A E5 BB D2 3D FA D3 62 A0 8B 4D 
32 A4 51 15 54 2E 23 E4 9B 35 46 58 33 38 CD 8B 
8B A4 2E F2 89 B2 E4 47 E9 BF 6E AF 7F 24 D0 25 
65 D2 24 AB DD D6 D2 F4 4A 6F 28 16 A4 32 31 96 
94 2D F2 0D ED 8F 10 02 45 24 E1 B2 F0 2F 4A D0 
C1 CB F7 C7 78 27 0B CD 70 8E BF A0 49 38 4E DE 
EF 24 C0 84 DA 3C A2 EE 14 6C A5 79 CC 42 AE E7 
F6 D4 B0 F5 9E 58 43 A5 19 32 9B EB 5F 97 66 07 
"""

e_hex = "01 00 01"

m_hex = """
1E 8A DB 08 E9 8A 58 01 2C 55 A8 C4 19 74 7B D8 
D8 DB 40 FA C2 40 DA 92 BF 48 74 F7 9E 9A D7 3B 
20 A9 34 07 0C AA 60 C7 67 25 41 68 AB EB 37 95 
56 18 45 8F 6B F9 4B 2D 7B A8 92 1D E7 E8 4F A6 
7A F7 E0 D6 FE 9E DD 55 4A BF 44 18 F7 AE E8 D8 
29 E6 EC 12 45 CF CB AF 58 96 67 96 3B 53 1B 89 
AF 63 87 9C 9A 65 31 76 A0 3B A6 89 BC 5D D4 5D 
A6 63 91 0A 19 FA 49 6A 6A EF B3 F9 AD FF F6 96 
"""

s_faulty_hex = """
25 72 EE 15 57 9D 2E 18 72 4E 98 A1 37 BC 82 CC 
46 65 4E 04 E0 AF 22 7C 36 D7 B0 C2 9E F4 9D 1B 
77 57 A3 67 71 2E BC 6C 8D AD 7E 52 66 78 86 0C 
CD 44 AF FB E0 C3 79 1F 4E 0B A3 E1 86 33 03 E8 
07 CC 4B D8 A8 95 42 B2 21 58 D6 7D 99 DC 93 05 
0A CA 58 4D 2D 06 95 0B 6D C6 15 7E 47 CF ED 4D 
C6 D8 77 E4 7A 0C 7F 1A 09 FE A4 11 5E BF 67 EF 
DA F4 A8 40 96 89 05 43 66 E5 87 86 E7 4D 2A BD 
"""


N = hex_to_int(N_hex)
e = hex_to_int(e_hex)
m = hex_to_int(m_hex)
s_faulty = hex_to_int(s_faulty_hex)


q = math.gcd(N, m - pow(s_faulty, e, N))


p = N // q


d = pow(e, -1, (p - 1) * (q - 1))


assert p * q == N, "incorrect"


print(f"p = {hex(p)}")
print(f"q = {hex(q)}")
print(f"d = {hex(d)}")


p = 0xd4693216ca3210f1491477d556e709141f6b5ea57e8b64a51011190d607b6b92a601857e4ad26e2b45123804ebdd08ccd15b0e50edcdc8754d5b2bb99dc8286087
q = 0xeacd987fce4c2815b8e1f6557a4120cd822763baa732e6fbd2d35d61b85f8278263ce068cddf6099ba885cda0b4ed1c2374de5d34b265fec3358611905ae81
d = 0x6f7345e591342f162230a8b392814b0f4f80268e7008b129cf0c4c009ad4cce91e6a3f1d2a5eb72ed86e55b079a8a2963248640819b1121f0411d0ba1b1647445bf2438288738d9ecaef90ed7b3a4d1170f22f28cc60396854b9508df0cc39397bbc4eae35428edb25416b6370bda32bc8d58ac6fceef0b3d94a0d65c7ef1501


In [4]:
import numpy as np


ctext_path = "aes-dfa/ctext.bin"
ftext_path = "aes-dfa/ftext.bin"
ptext_path = "aes-dfa/ptext.bin"


ctext = np.fromfile(ctext_path, dtype=np.uint8).reshape(1000, 16)
ftext = np.fromfile(ftext_path, dtype=np.uint8).reshape(1000, 16)
ptext = np.fromfile(ptext_path, dtype=np.uint8).reshape(1000, 16)


def get_successful_glitches():
    return np.sum(np.any(ctext != ftext, axis=1))

successful_glitches = get_successful_glitches()
success_rate = successful_glitches / 1000 * 100


print(f"The number of successful glitches is {successful_glitches}")
print(f"Success rate: {success_rate:.2f}%")


The number of successful glitches is 402
Success rate: 40.20%


In [5]:
import numpy as np


ctext_path = "aes-dfa/ctext.bin"
ftext_path = "aes-dfa/ftext.bin"


ctext = np.fromfile(ctext_path, dtype=np.uint8).reshape(1000, 16)
ftext = np.fromfile(ftext_path, dtype=np.uint8).reshape(1000, 16)


def classify_fault_pairs():
    column_1 = []  
    column_2 = []  
    column_3 = []  
    column_4 = []  

    
    def is_fault_in_column(xor_result, column_index):
       
        column_map = {
            1: [0, 7, 10, 13],
            2: [1, 4, 11, 14],
            3: [2, 5, 8, 15],
            4: [3, 6, 9, 12]
        }

        positions = column_map.get(column_index, [])
        return all(xor_result[pos] != 0 for pos in positions)

   
    for idx in range(1000):
        if np.any(ctext[idx] != ftext[idx]): 
            xor_result = np.bitwise_xor(ctext[idx], ftext[idx]) 

            
            if is_fault_in_column(xor_result, 1):
                column_1.append([ctext[idx], ftext[idx]])
            if is_fault_in_column(xor_result, 2):
                column_2.append([ctext[idx], ftext[idx]])
            if is_fault_in_column(xor_result, 3):
                column_3.append([ctext[idx], ftext[idx]])
            if is_fault_in_column(xor_result, 4):
                column_4.append([ctext[idx], ftext[idx]])

    return column_1, column_2, column_3, column_4

#
def get_faulty_pairs_by_column(pair_count=2):
    col_1, col_2, col_3, col_4 = classify_fault_pairs()

    
    column_1_pairs = col_1[:pair_count]
    column_2_pairs = col_2[:pair_count]
    column_3_pairs = col_3[:pair_count]
    column_4_pairs = col_4[:pair_count]

    return {'column_1': column_1_pairs, 'column_2': column_2_pairs, 'column_3': column_3_pairs, 'column_4': column_4_pairs}


def convert_to_hex(byte_array):
    return ''.join(format(byte, '02x') for byte in byte_array)


def display_pairs_in_hex():
    faulty_pairs = get_faulty_pairs_by_column()

    hex_faulty_pairs = {}
    for col, pairs in faulty_pairs.items():
        hex_faulty_pairs[col] = []
        for c, f in pairs:
            c_hex = convert_to_hex(c)
            f_hex = convert_to_hex(f)
            hex_faulty_pairs[col].append((c_hex, f_hex))

    return hex_faulty_pairs


hex_pairs = display_pairs_in_hex()

for col, pairs in hex_pairs.items():
    print(f"Column {col}:")
    for idx, (c, f) in enumerate(pairs):
        print(f"  Pair {idx + 1}: Ciphertext: {c}, Faulty Ciphertext: {f}")


Column column_1:
  Pair 1: Ciphertext: 23db99defc61747b8c5f36651b7f261e, Faulty Ciphertext: 33db99defc6174f68c5fa3651b2e261e
  Pair 2: Ciphertext: e5992aabc2d122a6de020bcd537ead0f, Faulty Ciphertext: 95992aabc2d1229ade0222cd5356ad0f
Column column_2:
  Pair 1: Ciphertext: 729002061e1383e8fca65142e902cab4, Faulty Ciphertext: 72d70206441383e8fca651e9e90243b4
  Pair 2: Ciphertext: 5cc1b561e70bd538b1761bed86b4dc26, Faulty Ciphertext: 5c89b561f00bd538b1761bf186b49126
Column column_3:
  Pair 1: Ciphertext: bb4f38f6cae5b63bb130e8db5db06342, Faulty Ciphertext: bb4fcaf6caddb63b7530e8db5db06355
  Pair 2: Ciphertext: ecb49e914cac9e83f1e1f95be0874d10, Faulty Ciphertext: ecb4d4914c4c9e83ede1f95be0874d48
Column column_4:
  Pair 1: Ciphertext: b6dc67dbc6f7632c1a160ea4c74485c7, Faulty Ciphertext: b6dc6715c6f7602c1a240ea4aa4485c7
  Pair 2: Ciphertext: 3bcdd2b4dc96676afbd8718d4ea9bf0d, Faulty Ciphertext: 3bcdd219dc96196afbae718d71a9bf0d


# DFA by Piret and Quisquater

This template is constructed to aid with implementing both the `simple` and `full` DFA variants needed for the homework.

In [6]:
SBOX = np.array([
        0x63, 0x7C, 0x77, 0x7B, 0xF2, 0x6B, 0x6F, 0xC5, 0x30, 0x01, 0x67, 0x2B, 0xFE, 0xD7, 0xAB, 0x76,
        0xCA, 0x82, 0xC9, 0x7D, 0xFA, 0x59, 0x47, 0xF0, 0xAD, 0xD4, 0xA2, 0xAF, 0x9C, 0xA4, 0x72, 0xC0,
        0xB7, 0xFD, 0x93, 0x26, 0x36, 0x3F, 0xF7, 0xCC, 0x34, 0xA5, 0xE5, 0xF1, 0x71, 0xD8, 0x31, 0x15,
        0x04, 0xC7, 0x23, 0xC3, 0x18, 0x96, 0x05, 0x9A, 0x07, 0x12, 0x80, 0xE2, 0xEB, 0x27, 0xB2, 0x75,
        0x09, 0x83, 0x2C, 0x1A, 0x1B, 0x6E, 0x5A, 0xA0, 0x52, 0x3B, 0xD6, 0xB3, 0x29, 0xE3, 0x2F, 0x84,
        0x53, 0xD1, 0x00, 0xED, 0x20, 0xFC, 0xB1, 0x5B, 0x6A, 0xCB, 0xBE, 0x39, 0x4A, 0x4C, 0x58, 0xCF,
        0xD0, 0xEF, 0xAA, 0xFB, 0x43, 0x4D, 0x33, 0x85, 0x45, 0xF9, 0x02, 0x7F, 0x50, 0x3C, 0x9F, 0xA8,
        0x51, 0xA3, 0x40, 0x8F, 0x92, 0x9D, 0x38, 0xF5, 0xBC, 0xB6, 0xDA, 0x21, 0x10, 0xFF, 0xF3, 0xD2,
        0xCD, 0x0C, 0x13, 0xEC, 0x5F, 0x97, 0x44, 0x17, 0xC4, 0xA7, 0x7E, 0x3D, 0x64, 0x5D, 0x19, 0x73,
        0x60, 0x81, 0x4F, 0xDC, 0x22, 0x2A, 0x90, 0x88, 0x46, 0xEE, 0xB8, 0x14, 0xDE, 0x5E, 0x0B, 0xDB,
        0xE0, 0x32, 0x3A, 0x0A, 0x49, 0x06, 0x24, 0x5C, 0xC2, 0xD3, 0xAC, 0x62, 0x91, 0x95, 0xE4, 0x79,
        0xE7, 0xC8, 0x37, 0x6D, 0x8D, 0xD5, 0x4E, 0xA9, 0x6C, 0x56, 0xF4, 0xEA, 0x65, 0x7A, 0xAE, 0x08,
        0xBA, 0x78, 0x25, 0x2E, 0x1C, 0xA6, 0xB4, 0xC6, 0xE8, 0xDD, 0x74, 0x1F, 0x4B, 0xBD, 0x8B, 0x8A,
        0x70, 0x3E, 0xB5, 0x66, 0x48, 0x03, 0xF6, 0x0E, 0x61, 0x35, 0x57, 0xB9, 0x86, 0xC1, 0x1D, 0x9E,
        0xE1, 0xF8, 0x98, 0x11, 0x69, 0xD9, 0x8E, 0x94, 0x9B, 0x1E, 0x87, 0xE9, 0xCE, 0x55, 0x28, 0xDF,
        0x8C, 0xA1, 0x89, 0x0D, 0xBF, 0xE6, 0x42, 0x68, 0x41, 0x99, 0x2D, 0x0F, 0xB0, 0x54, 0xBB, 0x16
], dtype=np.uint8)

# Inverse of AES SBOX
ISBOX = SBOX.argsort()

# AES MixCols matrix
MIXCOLS = np.array([[2, 3, 1, 1],
                    [1, 2, 3, 1],
                    [1, 1, 2, 3],
                    [3, 1, 1, 2]])



In [7]:
# Check if you got the right answer for the 4 keybytes in the first column (key at indices [0, 13, 10, 7])
# Note: We're referring to the round 10 keybytes (no need to rewind with the the key schedule)
# Note: The same key is used both for the `simple` and `full` DFA

def check_keybytes(k_0: int, k_13: int, k_10: int, k_7: int):
    keybytes = bytes([k_0, k_13, k_10, k_7])
    hasher = hashlib.sha3_256()
    hasher.update(keybytes)
    key_hash = hasher.hexdigest()
    if key_hash == '4409976e63e88e6d0ef93405e6b6d678c2a498d22dcaa72b28c8c9cd6233ec7f':
        print("Congratulations! Correct 4 keybytes found")
        return True
    
    print("Not quite right")
    return False

In [8]:
# Two pairs of ciphertext/faulty texts.
# The fault is injected in the *first byte* before the MixCols in the 9th round
# Note: use for `simple` DFA (part C)

simple_ctxt1 = [174, 44, 204, 43, 18, 196, 238, 88, 3, 227, 92, 0, 137, 106, 205, 88]
simple_ftxt1 = [128, 44, 204, 43, 18, 196, 238, 171, 3, 227, 159, 0, 137, 186, 205, 88]

simple_ctxt2 = [41, 4, 148, 29, 23, 74, 41, 127, 125, 148, 36, 219, 29, 127, 4, 58]
simple_ftxt2 = [186, 4, 148, 29, 23, 74, 41, 160, 125, 148, 59, 219, 29, 172, 4, 58]


# Load ctext/ftext pairs in the correct AES column order
simple_ctxt1 = np.reshape(simple_ctxt1, (4, 4), order='F').astype(np.uint8)
simple_ftxt1 = np.reshape(simple_ftxt1, (4, 4), order='F').astype(np.uint8)

simple_ctxt2 = np.reshape(simple_ctxt2, (4, 4), order='F').astype(np.uint8)
simple_ftxt2 = np.reshape(simple_ftxt2, (4, 4), order='F').astype(np.uint8)

print("First pair diff:")
print(simple_ctxt1 ^ simple_ftxt1)
first_pair_simple = (simple_ctxt1, simple_ftxt1)

print("Second pair diff:")
print(simple_ctxt2 ^ simple_ftxt2)
second_pair_simple = (simple_ctxt2, simple_ftxt2)

First pair diff:
[[ 46   0   0   0]
 [  0   0   0 208]
 [  0   0 195   0]
 [  0 243   0   0]]
Second pair diff:
[[147   0   0   0]
 [  0   0   0 211]
 [  0   0  31   0]
 [  0 223   0   0]]


In [9]:
# Load all plaintexts/ciphertexts/faultytexts in the correct AES column order
# Note: not needed for the `simple` DFA (part C) 

row_type = np.dtype((np.uint8, (4, 4)))
all_ctext = np.fromfile("aes-dfa/ctext.bin", dtype=row_type).transpose(0, 2, 1)
all_ptext = np.fromfile("aes-dfa/ptext.bin", dtype=row_type).transpose(0, 2, 1)
all_ftext = np.fromfile("aes-dfa/ftext.bin", dtype=row_type).transpose(0, 2, 1)

print(all_ctext[0] ^ all_ftext[0])

[[  0   0   0 109]
 [  0   0  50   0]
 [  0   3   0   0]
 [206   0   0   0]]


In [10]:
# Galois multiplication by 2 (for MixCols)
def galois_mult_2(a):
    temp = (a << 1) & 0xff

    if (a & 0x80):
        temp ^= 0x1b

    return temp

# Galois multiplication by 3 (for MixCols)
def galois_mult_3(a):
    return galois_mult_2(a) ^ a

In [11]:
# AES ShiftRows
# `mat` is 4x4 AES matrix
def shift(mat):
    shifted = np.zeros_like(mat)
    for i in range(4):
        shifted[i] = mat[i, np.arange(i, 4+i) % 4]
    return shifted

# TODO: implement your own. Should undo shift(mat)
def unshift(mat):
    pass


In [12]:
# Precompute all possible mixcols(glitch)
# TODO: Only works if glitch is in the first row! 
#       For `full` DFA need to add more entries to make it work for glitches in any row

D = []
mixcol = MIXCOLS[:, 0]
for x in range(1, 255+1):
    D_element = []
    for j in range(4):
        out = None
        if mixcol[j] == 1:
            out = x
        if mixcol[j] == 2:
            out = galois_mult_2(x)
        if mixcol[j] == 3:
            out = galois_mult_3(x)
        D_element.append(out)
    D.append(D_element)

print("Length of lookup table:", len(D))

Length of lookup table: 255


# Simple Attack Algorithm (finds 4 bytes):

## Variable Definitions
Let $c, c'$ be the first (ciphertext, faultytext) pair and $c, c^{*\prime}$ be the second pair.
Note: $c_0$ refers to the $0$ index byte of the ciphertext

## Preliminary Filtering
1. For each $K_0 \in 0 \text{ to } 255$ and $K_{13} \in 0 \text{ to } 255$, and $x \in 1 \text{ to } 255$
    - Check if $ISBOX(K_0 \oplus c_0) \oplus ISBOX(K_0 \oplus c_0') \stackrel{?}{=} D[x, 0]$
    - Check if $ISBOX(K_{13} \oplus c_{13}) \oplus ISBOX(K_{13} \oplus c_{13}') \stackrel{?}{=} D[x, 1]$

    - If both are true, add candidates $\{K_0, K_{13}\}$ to group $K_{c2}$
2. For each $K_{10} \in 0 \text{ to } 255$, and $\{K_{0}, K_{13}\} \in K_{c2}$, and $x \in 1 \text{ to } 255$
    - Check if $ISBOX(K_0 \oplus c_0) \oplus ISBOX(K_0 \oplus c_0') \stackrel{?}{=} D[x, 0]$
    - Check if $ISBOX(K_{13} \oplus c_{13}) \oplus ISBOX(K_{13} \oplus c_{13}') \stackrel{?}{=} D[x, 1]$
    - Check if $ISBOX(K_{10} \oplus c_{10}) \oplus ISBOX(K_{10} \oplus c_{10}') \stackrel{?}{=} D[x, 2]$

    - If so, add candidates $\{K_0, K_{13}, K_{10}\}$ to group $K_{c3}$
3. For each $K_{7} \in 0 \text{ to } 255$, and $\{K_{0}, K_{13}, K_{10}\} \in K_{c3}$, and $x \in 1 \text{ to } 255$
    - Check if $ISBOX(K_0 \oplus c_0) \oplus ISBOX(K_0 \oplus c_0') \stackrel{?}{=} D[x, 0]$
    - Check if $ISBOX(K_{13} \oplus c_{13}) \oplus ISBOX(K_{13} \oplus c_{13}') \stackrel{?}{=} D[x, 1]$
    - Check if $ISBOX(K_{10} \oplus c_{10}) \oplus ISBOX(K_{10} \oplus c_{10}') \stackrel{?}{=} D[x, 2]$
    - Check if $ISBOX(K_{7} \oplus c_{7}) \oplus ISBOX(K_{7} \oplus c_{7}') \stackrel{?}{=} D[x, 3]$

    - If so, add candidates $\{K_0, K_{13}, K_{10}, K_{7}\}$ to group $K_{c4}$
    
## Finding Final Candidate
1. For each $\{K_{0}, K_{13}, K_{10}, K_7\} \in K_{c4}$, and $x \in 1 \text{ to } 255$
  - $ISBOX(K_0 \oplus c^{*}_0) \oplus ISBOX(K_0 \oplus c^{*\prime}_0) \stackrel{?}{=} D[x, 0]$
  - $ISBOX(K_{13} \oplus c^{*}_{13}) \oplus ISBOX(K_{13} \oplus c^{*\prime}_{13}) \stackrel{?}{=} D[x, 1]$
  - $ISBOX(K_{10} \oplus c^{*}_{10}) \oplus ISBOX(K_{10} \oplus c^{*\prime}_{10}) \stackrel{?}{=} D[x, 2]$
  - $ISBOX(K_{7} \oplus c^{*}_{7}) \oplus ISBOX(K_{7} \oplus c^{*\prime}_{7}) \stackrel{?}{=} D[x, 3]$
  - If all are true $\{K_0, K_{13}, K_{10}, K_{7}\}$, are likely correct keybytes


# Indexing Tips:
You can access elements such as $c_{0}, c_{13}, c_{10}, c_{7}$ by using np.unravel() like this:

In [13]:
c13 = simple_ctxt1[np.unravel_index(13, shape=(4,4), order='F')]

In [14]:
def precompute_d_table():
    D = []  
    mixcol = MIXCOLS[:, 0]  
    for x in range(1, 256): 
        D_element = []
        for j in range(4): 
            out = None
            if mixcol[j] == 1:
                out = x  
            elif mixcol[j] == 2:
                out = galois_mult_2(x)  
            elif mixcol[j] == 3:
                out = galois_mult_3(x) 
            D_element.append(out)
        D.append(D_element)
    
    return np.array(D)  


D_table = precompute_d_table()

def extract_bytes_from_state(state, faulty_state, indices):
    state_bytes = [state[np.unravel_index(i, shape=(4, 4), order='F')] for i in indices]
    faulty_bytes = [faulty_state[np.unravel_index(i, shape=(4, 4), order='F')] for i in indices]
    
    if any(byte < 0 or byte > 255 for byte in state_bytes + faulty_bytes):
        raise ValueError(f"Extracted bytes are out of valid range: {state_bytes + faulty_bytes}")
    
    return state_bytes, faulty_bytes

def build_lookup_sets(D_table):
    set_2_bytes = {tuple(D_table[i, :2]) for i in range(len(D_table))}
    set_3_bytes = {tuple(D_table[i, :3]) for i in range(len(D_table))}
    set_4_bytes = {tuple(D_table[i, :4]) for i in range(len(D_table))}
    return set_2_bytes, set_3_bytes, set_4_bytes

lookup_set_2, lookup_set_3, lookup_set_4 = build_lookup_sets(D_table)


def simple_dfa_attack_v2(pairs, indices=[0, 7, 10, 13]):
    first_ctxt, first_ftxt = pairs[0]
    second_ctxt, second_ftxt = pairs[1]

    state_bytes, faulty_bytes = extract_bytes_from_state(first_ctxt, first_ftxt, indices)
    state_bytes_x, faulty_bytes_x = extract_bytes_from_state(second_ctxt, second_ftxt, indices)

    candidate_2 = []
    for byte_0 in range(256):
        for byte_13 in range(256):
            try:
                candidate_1 = (ISBOX[byte_0 ^ state_bytes[0]] ^ ISBOX[byte_0 ^ faulty_bytes[0]], 
                               ISBOX[byte_13 ^ state_bytes[3]] ^ ISBOX[byte_13 ^ faulty_bytes[3]])
                if tuple(candidate_1) in lookup_set_2:
                    candidate_2.append((byte_0, byte_13))
            except IndexError:
                continue

    candidate_3 = []
    for byte_10 in range(256):
        for byte_0, byte_13 in candidate_2:
            try:
                candidate_2_values = (ISBOX[byte_0 ^ state_bytes[0]] ^ ISBOX[byte_0 ^ faulty_bytes[0]], 
                                      ISBOX[byte_13 ^ state_bytes[3]] ^ ISBOX[byte_13 ^ faulty_bytes[3]], 
                                      ISBOX[byte_10 ^ state_bytes[2]] ^ ISBOX[byte_10 ^ faulty_bytes[2]])
                if tuple(candidate_2_values) in lookup_set_3:
                    candidate_3.append((byte_0, byte_13, byte_10))
            except IndexError:
                continue

    candidate_4 = []
    for byte_7 in range(256):
        for byte_0, byte_13, byte_10 in candidate_3:
            try:
                candidate_3_values = (ISBOX[byte_0 ^ state_bytes[0]] ^ ISBOX[byte_0 ^ faulty_bytes[0]], 
                                      ISBOX[byte_13 ^ state_bytes[3]] ^ ISBOX[byte_13 ^ faulty_bytes[3]], 
                                      ISBOX[byte_10 ^ state_bytes[2]] ^ ISBOX[byte_10 ^ faulty_bytes[2]], 
                                      ISBOX[byte_7 ^ state_bytes[1]] ^ ISBOX[byte_7 ^ faulty_bytes[1]])
                if tuple(candidate_3_values) in lookup_set_4:
                    candidate_4.append((byte_0, byte_13, byte_10, byte_7))
            except IndexError:
                continue

    candidate_5 = []
    for byte_0, byte_13, byte_10, byte_7 in candidate_4:
        try:
            candidate_4_values = (ISBOX[byte_0 ^ state_bytes_x[0]] ^ ISBOX[byte_0 ^ faulty_bytes_x[0]], 
                                  ISBOX[byte_13 ^ state_bytes_x[3]] ^ ISBOX[byte_13 ^ faulty_bytes_x[3]], 
                                  ISBOX[byte_10 ^ state_bytes_x[2]] ^ ISBOX[byte_10 ^ faulty_bytes_x[2]], 
                                  ISBOX[byte_7 ^ state_bytes_x[1]] ^ ISBOX[byte_7 ^ faulty_bytes_x[1]])
            if tuple(candidate_4_values) in lookup_set_4:
                candidate_5.append((byte_0, byte_13, byte_10, byte_7))
        except IndexError:
            continue

    return candidate_5  


result = simple_dfa_attack_v2([first_pair_simple, second_pair_simple], [0, 7, 10, 13])
print('The key bytes for the simple attack are:', result)


The key bytes for the simple attack are: [(168, 138, 164, 45)]


In [15]:
check_keybytes(k_0=168, k_13=138, k_10=164, k_7=45)

Congratulations! Correct 4 keybytes found


True

In [16]:
D = []
for i in range(4):
    mixcol = MIXCOLS[:, i]
    for x in range(1, 255+1):
        D_element = []
        for j in range(4):
            out = None
            if mixcol[j] == 1:
                out = x
            if mixcol[j] == 2:
                out = galois_mult_2(x)
            if mixcol[j] == 3:
                out = galois_mult_3(x)
            D_element.append(out)
        D.append(D_element)

D = np.array(D)


D2digits  = []
for arr in range(len(D)):
    D2digits .append("".join(D[arr][:2].astype(str)))
D2digitsSet  = set(D2digits )


D3digits = []
for arr in range(len(D)):
    D3digits.append("".join(D[arr][:3].astype(str)))
D3digitsSet  = set(D3digits)


D4digits = []
for arr in range(len(D)):
    D4digits.append("".join(D[arr][:4].astype(str)))
D4digitsSet = set(D4digits)




In [17]:

def get_bytes_at_positions(ciphertext, faultytext, indices):
    return [
        (ciphertext[i], faultytext[i])  
        for i in indices
    ]


def extract_ciphertext_faultytext_pairs(col_index=None):
    columns = [[] for _ in range(4)]
    counter = 0

    for i in range(1000):
        if not np.all(ctext[i] == ftext[i]):
            xor = np.bitwise_xor(ctext[i], ftext[i])
            if all(xor[j] != 0 for j in [0, 7, 10, 13]):
                columns[0].append([ctext[i], ftext[i]])
                counter += 1
            if all(xor[j] != 0 for j in [1, 4, 11, 14]):
                columns[1].append([ctext[i], ftext[i]])
                counter += 1
            if all(xor[j] != 0 for j in [2, 5, 8, 15]):
                columns[2].append([ctext[i], ftext[i]])
                counter += 1
            if all(xor[j] != 0 for j in [3, 6, 9, 12]):
                columns[3].append([ctext[i], ftext[i]])
                counter += 1

    return columns[col_index - 1] if col_index else columns


def extract_pairs_for_column(pairs_count=2, col_index=None):
    return extract_ciphertext_faultytext_pairs(col_index=col_index)[:pairs_count]


def print_pairs_in_hex_for_column(column_no):
    arr_pairs = extract_pairs_for_column(col_index=column_no)
    return [[[hex(x) for x in ctext], [hex(x) for x in ftext]] for ctext, ftext in arr_pairs]


def get_all_pairs_for_all_columns(pairs_count=2):
    return {f'col_{i+1}': extract_pairs_for_column(pairs_count, i+1) for i in range(4)}

def full_attack_phase(pairs, indices):
    first_ctxt, first_ftxt = pairs[0]
    second_ctxt, second_ftxt = pairs[1]

    bytes_first = get_bytes_at_positions(first_ctxt, first_ftxt, indices)
    bytes_second = get_bytes_at_positions(second_ctxt, second_ftxt, indices)

    candidate_keys = []
    for k0 in range(256):
        for k1 in range(256):
            str_1 = str(ISBOX[k0 ^ bytes_first[0][0]] ^ ISBOX[k0 ^ bytes_first[0][1]]) + str(ISBOX[k1 ^ bytes_first[3][0]] ^ ISBOX[k1 ^ bytes_first[3][1]])
            if str_1 in D2digitsSet :
                candidate_keys.append((k0, k1))

    candidate_keys_phase_2 = []
    for k2 in range(256):
        for k0, k1 in candidate_keys:
            str_2 = str(ISBOX[k0 ^ bytes_first[0][0]] ^ ISBOX[k0 ^ bytes_first[0][1]]) + str(ISBOX[k1 ^ bytes_first[3][0]] ^ ISBOX[k1 ^ bytes_first[3][1]]) + \
                    str(ISBOX[k2 ^ bytes_first[2][0]] ^ ISBOX[k2 ^ bytes_first[2][1]])
            if str_2 in D3digitsSet :
                candidate_keys_phase_2.append((k0, k1, k2))

    candidate_keys_phase_3 = []
    for k3 in range(256):
        for k0, k1, k2 in candidate_keys_phase_2:
            str_3 = str(ISBOX[k0 ^ bytes_first[0][0]] ^ ISBOX[k0 ^ bytes_first[0][1]]) + str(ISBOX[k1 ^ bytes_first[3][0]] ^ ISBOX[k1 ^ bytes_first[3][1]]) + \
                    str(ISBOX[k2 ^ bytes_first[2][0]] ^ ISBOX[k2 ^ bytes_first[2][1]]) + str(ISBOX[k3 ^ bytes_first[1][0]] ^ ISBOX[k3 ^ bytes_first[1][1]])
            if str_3 in D4digitsSet:
                candidate_keys_phase_3.append((k0, k1, k2, k3))

    candidate_keys_phase_4 = []
    for k0, k1, k2, k3 in candidate_keys_phase_3:
        str_4 = str(ISBOX[k0 ^ bytes_second[0][0]] ^ ISBOX[k0 ^ bytes_second[0][1]]) + str(ISBOX[k1 ^ bytes_second[3][0]] ^ ISBOX[k1 ^ bytes_second[3][1]]) + \
                str(ISBOX[k2 ^ bytes_second[2][0]] ^ ISBOX[k2 ^ bytes_second[2][1]]) + str(ISBOX[k3 ^ bytes_second[1][0]] ^ ISBOX[k3 ^ bytes_second[1][1]])
        if str_4 in D4digitsSet:
            candidate_keys_phase_4.append((k0, k1, k2, k3))

    
    if indices == [0, 7, 10, 13]:  
        return [(k0, k1, k2, k3) for k0, k1, k2, k3 in candidate_keys_phase_4]
    elif indices == [1, 4, 11, 14]:  
        return [(k3, k0, k1, k2) for k0, k1, k2, k3 in candidate_keys_phase_4]
    elif indices == [2, 5, 8, 15]:  
        return [(k2, k3, k0, k1) for k0, k1, k2, k3 in candidate_keys_phase_4]
    elif indices == [3, 6, 9, 12]:  
        return [(k1, k2, k3, k0) for k0, k1, k2, k3 in candidate_keys_phase_4]


col_pairs = get_all_pairs_for_all_columns()
result_phase_1 = full_attack_phase(col_pairs['col_1'], [0, 7, 10, 13])
result_phase_2 = full_attack_phase(col_pairs['col_2'], [1, 4, 11, 14])
result_phase_3 = full_attack_phase(col_pairs['col_3'], [2, 5, 8, 15])
result_phase_4 = full_attack_phase(col_pairs['col_4'], [3, 6, 9, 12])

print('First set of key bytes for Phase 1:', result_phase_1)
print('Second set of key bytes for Phase 2:', result_phase_2)
print('Third set of key bytes for Phase 3:', result_phase_3)
print('Fourth set of key bytes for Phase 4:', result_phase_4)

First set of key bytes for Phase 1: [(168, 138, 164, 45)]
Second set of key bytes for Phase 2: [(53, 73, 46, 0)]
Third set of key bytes for Phase 3: [(93, 213, 55, 198)]
Fourth set of key bytes for Phase 4: [(170, 35, 50, 172)]


In [18]:
# After recovering the full key, decrypt the secret message:
# You can use the `pycryptodome` library 
from Crypto.Cipher import AES


all_keys = [168, 73, 55, 172, 53, 213, 50, 45, 93, 35, 164, 0, 170, 138, 46, 198]


keys_hex = [hex(x)[2:].zfill(2) for x in all_keys]  
keys_str = "".join(keys_hex)  
keys_byte = bytes.fromhex(keys_str)


original_key = aes.reverse_key_schedule(keys_byte, 10)
print("The original key is:", original_key)

secret = bytes.fromhex("2a92fc6ad8006b658f49062c2843ad99")
cipher = AES.new(original_key, AES.MODE_ECB)
plaintext = cipher.decrypt(secret)

print("The secret message is:", plaintext.decode('utf-8'))

The original key is: b'=\x83\xa4\x01t\xa3Xg;l=\x99\xdcS\x92\xc3'
The secret message is: DFAIsAFunAttack!
